#!/usr/bin/env python3
#
# Copyright © 2020 Endless OS Foundation LLC.
#
# This file is part of clubhouse
# (see https://github.com/endlessm/clubhouse).
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Authors:
#       Joaquim Rocha <jrocha@endlessm.com>
#

import os


def _run_clubhouse():
    import signal
    import sys

    from gi.repository import GLib
    from eosclubhouse.clubhouse import ClubhouseApplication

    app = ClubhouseApplication()

    # Make sure the GTK+ event loop is quit if the script is interrupted (Ctrl+C)
    GLib.unix_signal_add(GLib.PRIORITY_DEFAULT, signal.SIGINT, app.quit)
    app.run(sys.argv)


if __name__ == '__main__':

    run_profile = os.environ.get("CLUBHOUSE_PROFILING", False)

    if run_profile:
        import cProfile

        prof = cProfile.Profile()
        res = prof.runcall(_run_clubhouse)
        prof.dump_stats("clubhouse-runstats")
    else:
        _run_clubhouse()
