#!/usr/bin/env python3
#
# Copyright (C) 2018 Endless Mobile, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Authors:
#       Joaquim Rocha <jrocha@endlessm.com>
#

import sys

from eosclubhouse.clubhouse import ClubhouseApplication

if __name__ == '__main__':
    # Make sure the GTK+ event loop is quit if the script is interrupted (Ctrl+C)
    import signal
    signal.signal(signal.SIGINT, signal.SIG_DFL)

    app = ClubhouseApplication()
    app.run(sys.argv)
