#!/usr/bin/env python3

# Tool to build and install a Flatpak containing all the Hack modules.
#
# Copyright (C) 2019 Endless Mobile, Inc.

from _common import run
from _clippy import main, CONFIG_FILE


if __name__ == "__main__":
    run(main, config_file=CONFIG_FILE)
