#!/bin/bash
#
# Convience script to check if the strings CSV are in sync with the
# strings in the spreadsheet.
#
# Copyright (c) 2019 Endless Mobile Inc.
#

quest_string_files=(data/quests_strings/*)
ignored_files=(data/quests_strings/remaining.csv)
check_files="${quest_string_files[@]/$ignored_files}"

./tools/get-strings-file
git diff --exit-code -- $check_files || ret=$?
git checkout -- $check_files
git checkout -- "${ignored_files[@]}"

if [ ! -z "$ret" ] && [ $ret -ne 0 ]; then
    message="The strings are not in sync. Please import them before commiting. Or to ignore this check, run: SKIP_STRINGS_CHECK=true git commit"
    echo -e "\e[01;31m$message\e[0m"
fi
exit $ret
