#!/usr/bin/env python

import argparse
import csv
import io
import os
import requests
import subprocess

QUESTS_PATH = os.path.join('eosclubhouse', 'quests')
CSV_PATH = os.path.join('data', 'quests_strings')

URL_TEMPLATE = ('https://docs.google.com/spreadsheets/d/{key}/' +
                'gviz/tq?tqx=out:csv&sheet={sheet}&range={range}')
URL_PARAMS = {
    'key': '162yiw_kW3lgLEIUwBq3PgiZxWTtcVBUHqpZKUXtF8qY',
    'sheet': 'Dialog',
    'range': 'A:E',
}

quest_codes = None


def get_quest_codes():
    global quest_codes
    if quest_codes is not None:
        return quest_codes

    quest_codes = set()
    for episode in os.listdir(QUESTS_PATH):
        episode_path = os.path.join(QUESTS_PATH, episode)
        if not os.path.isdir(episode_path):
            continue
        for filename in os.listdir(episode_path):
            if filename == '__init__.py' or filename.startswith('questset_'):
                continue
            code, _ext = os.path.splitext(filename)
            quest_codes.add(code)

    quest_codes = list(quest_codes)
    return quest_codes


def get_rows_from_sheet(sheet=None):
    url_params = URL_PARAMS
    if sheet is not None:
        url_params['sheet'] = sheet

    url = URL_TEMPLATE.format(**url_params)
    response = requests.get(url)
    response.raise_for_status()
    csv_file = io.StringIO(response.text)
    return list(csv.reader(csv_file))


def _get_rows_for_quest(quest, rows):
    return (r for r in rows if r[0].startswith(quest.upper()))


def _write_csv_file(filename, rows):
    if not rows:
        return

    with open(filename, 'w') as out_file:
        writer = csv.writer(out_file)
        for r in rows:
            writer.writerow(r)


def write_quests(quests, rows):
    remaining_rows = None
    if quests is None:
        quests = get_quest_codes()
        remaining_rows = {r[0]: r for r in rows}

    os.makedirs(CSV_PATH, exist_ok=True)
    for quest in quests:
        quest_rows = list(_get_rows_for_quest(quest, rows))
        if remaining_rows is not None:
            for r in quest_rows:
                del remaining_rows[r[0]]
        filename = os.path.join(CSV_PATH, quest + '.csv')
        _write_csv_file(filename, quest_rows)

    if remaining_rows is not None:
        remaining_rows = list(remaining_rows.values())
        remaining_rows.sort()
        filename = os.path.join(CSV_PATH, 'noquest.csv')
        _write_csv_file(filename, remaining_rows)


def _build_commit_message(sheet, quests=None):
    if sheet is None:
        sheet = URL_PARAMS['sheet']

    quests_string = 'all'
    if quests is not None:
        quests_string = ', '.join(quests)

    head = 'data: Update quests strings CSV'
    body = 'From sheet {}.'.format(sheet)
    body += '\n\n'
    body += 'Quests requested for import: {}'.format(quests_string)
    return head + '\n\n' + body


def make_commit(sheet, quests):
    message = _build_commit_message(sheet, quests)

    # Ensure we don't include previously added things in this commit
    subprocess.call(['git', 'reset', 'HEAD'])

    # Add any changes to the CSV file and commit them
    subprocess.call(['git', 'add', os.path.join(CSV_PATH, '*.csv')])
    subprocess.call(['git', 'commit', '--no-verify', '-m', message])


def main(sheet, quests=None, commit=False):
    rows = get_rows_from_sheet(sheet)
    write_quests(quests, rows)
    if not commit:
        return
    make_commit(sheet, quests)


parser = argparse.ArgumentParser(description='Obtain the strings to be used in quest messages.')
parser.add_argument('--sheet', type=str,
                    help='Obtain strings from this sheet.')
parser.add_argument('--quests', type=str,
                    metavar='QUEST',
                    nargs='+',
                    help=('Get only the strings for the specified quests. ' +
                          'Strings that are not specific to any quest will only be obtained ' +
                          'if this parameter is not passed.'))
parser.add_argument('--commit', action='store_true',
                    help='Make a commit with the updated strings.')

args = parser.parse_args()
available_quests = get_quest_codes()

if args.quests is not None:
    bad_quests = set(args.quests) - set(available_quests)
    if bad_quests:
        parser.error(('The following quests are not available: {}.\n' +
                      'Available quests: {}').format(bad_quests, available_quests))

main(**vars(args))
