#!/bin/bash
#
# Convience script to run flake8 with config file and in the right place.
#
# Copyright (c) 2018 Endless Mobile Inc.
#
# Author: Joaquim Rocha <jrocha@endlessm.com>
#

source_dir="$(git rev-parse --show-toplevel)"

pushd "$source_dir"

source tools/setup-venv

setup_venv

flake8 --config=flake8.cfg $@ || ret=$?

popd

if [ ! -z "$ret" ] && [ $ret -ne 0 ]; then
    message="There are lint errors. Please fix the errors above and try to commit again."
    echo -e "\e[01;31m$message\e[0m"
fi
exit $ret
