#!/bin/bash -e
#
# Setup git hooks.
#
# Copyright (c) 2018 Endless Mobile Inc.
#
# Author: Joaquim Rocha <jrocha@endlessm.com>
#

# Pre-commit hook

source_dir="$(git rev-parse --show-toplevel)"
precommit_hook_file="$source_dir/.git/hooks/pre-commit"

source "$source_dir/tools/setup-lint"
setup_lint || true
echo "Installing git pre-commit hook"

cp "$source_dir/tools/pre-commit.in" "$precommit_hook_file"
chmod +x "$precommit_hook_file"

# End pre-commit hook
