#!/bin/bash

echo "Resetting com.hack_computer.GameStateService"
gdbus call --session \
    --dest com.hack_computer.GameStateService \
    --object-path /com/hack_computer/GameStateService \
    --method com.hack_computer.GameStateService.Reset

echo "Resetting the hack-mode"
gsettings reset org.gnome.shell hack-mode-enabled

echo "Removing com.hack_computer.Fizzics state"
flatpak-spawn --host rm -rf ~/.var/app/com.hack_computer.Fizzics/data/webkitgtk/localstorage/

echo "Resetting desktop icons"
flatpak-spawn --host eos-reset-desktop

echo "Resetting cursor"
gsettings reset org.gnome.desktop.interface cursor-size
gsettings reset org.gnome.desktop.interface cursor-theme

echo "Resetting the desktop background"
gsettings reset org.gnome.desktop.background picture-uri
gsettings reset com.hack_computer.clubhouse hack-mode-disabled-picture-uri

echo "Resetting wobbly windows"
gsettings reset org.gnome.shell wobbly-effect
gsettings reset org.gnome.shell wobbly-object-movement-range
gsettings reset org.gnome.shell wobbly-slowdown-factor
gsettings reset org.gnome.shell wobbly-spring-friction
gsettings reset org.gnome.shell wobbly-spring-k

echo "Done"
