#!/bin/bash

echo "Resetting com.endlessm.GameStateService"
gdbus call --session \
    --dest com.endlessm.GameStateService \
    --object-path /com/endlessm/GameStateService \
    --method com.endlessm.GameStateService.Reset

echo "Removing com.endlessm.Fizzics state"
flatpak-spawn --host rm -rf ~/.var/app/com.endlessm.Fizzics/data/webkitgtk/localstorage/

echo "Resetting desktop icons"
flatpak-spawn --host eos-reset-desktop

echo "Resetting cursor"
gsettings reset org.gnome.desktop.interface cursor-size
gsettings reset org.gnome.desktop.interface cursor-theme

echo "Resetting wobbly windows"
dconf reset /org/gnome/shell/wobbly-effect
dconf reset /org/gnome/shell/wobbly-object-movement-range
dconf reset /org/gnome/shell/wobbly-slowdown-factor
dconf reset /org/gnome/shell/wobbly-spring-frictiont
dconf reset /org/gnome/shell/wobbly-spring-k

echo "Done"
